### PR TITLE
Adding empty methods from AbstractProvider

### PR DESCRIPTION
**Pull request by patrickconroy**
Otherwise this errors out complaining about those missing methods

### CODE REVIEW

**Comment by stevenmaguire** [comment]
@patrickconroy can you share more information about the errors? I want to understand from where the missing methods are being called?

**Comment by patrickconroy** [comment]
It looks like if you want to use the master branch of https://github.com/thephpleague/oauth2-client, the `AbstractProvider` there has a few new methods.. https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php

And sorry I missed the notification about this..

**Comment by stevenmaguire** [comment]
Gotcha. I'll take a look. This package hasn't been used very much yet, as it was merely migrated from the core package in preparation for a 1.0 release.

**Comment by stevenmaguire** [comment]
The current 0.1.0 release of this package is configured to work with the current stable version of the league's core package, which also includes the Microsoft Provider. 

I've upgraded the master branch of this package to be compatible with `"league/oauth2-client": "~1.0@dev"`.

Checkout the latest on master.

**Comment by patrickconroy** [comment]
Awesome thank you!

**Pull request closed without merging**
